name = "model-battle"
main = "functions/api/[[route]].ts"
compatibility_date = "2024-01-01"

[build]
command = "npm run build"
watch_dir = "src"

[site]
bucket = "dist"

[env.production]
name = "model-battle-prod"

[env.staging]
name = "model-battle-staging" 