name = "model-battle"
compatibility_date = "2024-01-01"

[build]
command = "npm run build"
dist = "dist"
watch_dir = "src"

[site]
bucket = "dist"
entry-point = "functions/api/[[route]].ts"

[env.production]
name = "model-battle-prod"

[env.staging]
name = "model-battle-staging" 